name: iOS SDK Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Check available simulator runtimes
      run: |
        xcrun simctl list runtimes
        echo "Available device types:"
        xcrun simctl list devicetypes
    
    - name: Create iOS simulator
      run: |
        RUNTIME=$(xcrun simctl list runtimes | grep iOS | tail -1 | cut -d ' ' -f 7)
        DEVICE=$(xcrun simctl list devicetypes | grep iPhone | tail -1 | cut -d ' ' -f 1)
        echo "Using runtime: $RUNTIME and device: $DEVICE"
        
        UDID=$(xcrun simctl create "Test Device" "$DEVICE" "$RUNTIME")
        echo "Created simulator with UDID: $UDID"
        echo "SIMULATOR_UDID=$UDID" >> $GITHUB_ENV
        
        xcrun simctl boot $UDID
    
    - name: Generate Xcode project
      run: swift package generate-xcodeproj
    
    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild test \
          -project PulseInsights.xcodeproj \
          -scheme "PulseInsights-Package" \
          -destination "platform=iOS Simulator,id=$SIMULATOR_UDID" \
          -sdk iphonesimulator \
          ONLY_ACTIVE_ARCH=YES | xcpretty