name: iOS SDK Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Get iOS SDK Path
      run: |
        IOS_SDK_PATH=$(xcrun --sdk iphonesimulator --show-sdk-path)
        echo "iOS SDK Path: $IOS_SDK_PATH"
        
        IOS_VERSION=$(xcrun simctl list runtimes | grep iOS | tail -1 | sed -E 's/.*iOS ([0-9]+\.[0-9]+).*/\1/')
        echo "iOS Version: $IOS_VERSION"
    
    - name: Build and Test with Swift Package Manager
      run: |
        swift test \
          -Xswiftc "-sdk" -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
          -Xswiftc "-target" -Xswiftc "x86_64-apple-ios$IOS_VERSION-simulator"